### ISSUE TITLE
Change backend colour to white

### ISSUE THREAD

**Issue by AlexSolbergRam** [Ramboll/ppm_rdk-gamificationplatform-sdk_unity#16]
Gamification site has its own scss files that inherit from the ramrisk ones and override a lot of values... So it is likely just a matter of removing the overrides to fallback to the ramrisk ones, rather than adding new rules

**Comment by iustin94** [comment]
Seems a bit more work than simply changing the background color. The UI code might not be properly structured to have that be the only change needed. There are small tweaks and adjustments to be made in multiple places to replicate the same look and feel. Progress is being done however.

**Comment by iustin94** [comment]
Right, what I mean by structure is the .css classes and such, not the .html structure, but more the inheritance that the .css files create. So yes it would be color changes

**Comment by iustin94** [comment]
Damn, first try!
