### ISSUE TITLE
Choose image from gallery or use camera

### ISSUE THREAD

**Issue by AlexSolbergRam** [Ramboll/ppm_rdk-gamificationplatform-sdk_unity#21]

**Comment by eldamir** [comment]
This one is ready for you to check, @AlexSolbergRam 



![Image](https://user-images.githubusercontent.com/2298514/171153850-ca78147f-bcfe-44ea-b87e-f709e955f63f.png)

**Comment by eldamir** [comment]
@AlexSolbergRam can you find time to checkout this feature and get it merged? I'd like to close the issue and consider it handled 😉

**Comment by AlexSolbergRam** [comment]
Sure. I haven't been at the 'office' since 2 June, so I have a lot to follow up on. I have set time aside for it Monday!
