### ISSUE TITLE
Stay logged in when game is completed

### ISSUE THREAD

**Issue by AlexSolbergRam** [Ramboll/ppm_rdk-gamificationplatform-sdk_unity#34]
- [X] Make sure user is still logged in when exiting a game
- [x] Get more descriptive error messages when login fails
- [x] Make sure password is saved when registering an account. Users often forget their password after their first run
- [x] Remember which campaign was active, so that when exiting a game, we are logged in to the right campaign
- [x] Always save password and don't make it a choice!

**Comment by eldamir** [comment]
@AlexSolbergRam What points were we missing here? We made it work, but we discussed also:

- More descriptive error messages when login fails
- ..?

**Comment by AlexSolbergRam** [comment]
...And make sure that the password is saved when creating the account - or that the credentials are not checked on "game completed". It still signs out when game is completed

**Comment by eldamir** [comment]
@AlexSolbergRam  Should we just always remember passwords and not make it a choice for the user? We don't want them to share devices anyway, so is there a good reason for letting them choose to **not** save the password?

Most apps these days just login once and then remember forever

**Comment by eldamir** [comment]
Everything was more or less already done. Added the "Just open the active campaign when leaving game instead of the project list" thingy, but the rest was already there.

Ready for review in the "new-ui-system" branch
