### ISSUE TITLE
Reorganize I2 localization spreadsheet.

### ISSUE THREAD

**Issue by marcusdyrholm** [Ramboll/ppm_rdk-gamificationplatform-sdk_unity#64]
Make it so the spreadsheet is more organized in different tabs.

**Comment by eldamir** [comment]
Won't that break next time we sync from Unity?

**Comment by marcusdyrholm** [comment]
It shouldn't break anything. I am doing all my testing on the renovation i2 spreadsheet at the moment and won't do any changes to the main sheet before i'm confident that it won't mess anything up in the current version that is up on the app store.
