### ISSUE TITLE
Localization of videos (safety-engine.com)

### ISSUE THREAD

**Issue by AlexSolbergRam** [Ramboll/ppm_rdk-gamificationplatform-sdk_unity#78]

**Comment by AlexSolbergRam** [comment]
This should be done in this sprint (19 sept -->).

**Comment by eldamir** [comment]
![Image](https://user-images.githubusercontent.com/2298514/192288924-7ccf964b-4f30-456f-bf62-15e688f97839.png)


This is a mockup of the UI I'm considering... Basically:

- A row per content_id per language. So the same controls for each version, like we're used to
- Languages can collapse into one row, showing just the status of the English version (the default), and the number of uploaded alternatives. Then it can be clicked to expand it and manage the alternatives
    - This will mean that we'll assume that current overrides are English versions, so after release, this will take some fiddling to move the videos into the right slots, but should be managable

/cc @AlexSolbergRam
